// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetBenchmarkProgress(arg1:number):Promise<string>;

export function GetBenchmarks():Promise<Array<models.Benchmark>>;

export function GetFavoriteBenchmarks():Promise<Array<string>>;

export function GetRecentScenarios(arg1:number):Promise<Array<models.ScenarioRecord>>;

export function GetSettings():Promise<models.Settings>;

export function Greet(arg1:string):Promise<string>;

export function LaunchKovaaksScenario(arg1:string,arg2:string):Promise<boolean|string>;

export function ResetSettings():Promise<boolean|string>;

export function SetFavoriteBenchmarks(arg1:Array<string>):Promise<boolean|string>;

export function StartWatcher(arg1:string):Promise<boolean|string>;

export function StopWatcher():Promise<boolean|string>;

export function UpdateSettings(arg1:models.Settings):Promise<boolean|string>;
